### ISSUE TITLE
Does not build on ubuntu 15 32-bit

### ISSUE THREAD

**Issue by johnterickson** [oakes/neovim-rs#1]
Looks like an integer-size mismatch:

   Compiling neovim-rs v0.1.0 (file:///home/john/Projects/neovim-rs)
src/lib.rs:131:80: 131:99 error: mismatched types:
 expected `u32`,
    found `u64`
(expected u32,
    found u64) [E0308]
src/lib.rs:131         let vim_str = ffi::C_String {data: method.as_ptr() as *const i8, size: method.len() as u64};
                                                                                              ^~~~~~~~~~~~~~~~~~~
src/lib.rs:143:15: 143:35 error: mismatched types:
 expected `u32`,
    found `u64`
(expected u32,
    found u64) [E0308]
src/lib.rs:143         size: message.len() as u64
                             ^~~~~~~~~~~~~~~~~~~~

**Comment by oakes** [comment]
I thought [size_t was defined as `u64`](http://doc.rust-lang.org/libc/libc/types/os/arch/c95/type.size_t.html), so I wonder why it is being interpreted as `u32` here.

**Comment by johnterickson** [comment]
Discalimer: I am new to Rust. It doesn't look like usize  works either which I would have thought would have been the right match. Once I get the nightly compiler installed (1.0 won't let me use the unstable features), I will play around with it some more. 

-----Original Message-----

**Comment by vi** [comment]
Reproducible for me as well. Changing `u64` to `u32` in error places and adding one more `as u64` make the compilation get though.

**Comment by oakes** [comment]
I updated libc and it looks like it is using `usize` everywhere now, so please try building it on a 32-bit machine and let me know if it's still an issue.
